# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(choices=[('TextAnswer', 'Text Answer'), ('YesNoAnswer', 'Yes/No Answer'), ('MultipleChoiceAnswer', 'Multiple Choice Answer')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=512)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questionaire.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=512, unique=True)),
                ('question_type', models.CharField(choices=[('TextQuestion', 'Text Question'), ('YesNoQuestion', 'Yes/No Question'), ('MultipleChoiceQuestion', 'Multiple Choice Question')], max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Questionaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=1028)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questionaire.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questionaire.Question')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='YesNoAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes', models.BooleanField()),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questionaire.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='YesNoQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questionaire.Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='questionaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionaire.Questionaire'),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questionaire.Question'),
        ),
        migrations.AddField(
            model_name='answerset',
            name='questionaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionaire.Questionaire'),
        ),
        migrations.AddField(
            model_name='answerset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionaire.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionaire.AnswerSet'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionaire.Question'),
        ),
    ]
