# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0002_auto_20160411_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='answerset',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='answerset',
            name='updated_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='updated_at',
            field=models.DateTimeField(editable=False),
        ),
    ]
