# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0003_auto_20160411_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='version',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
