# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0005_auto_20160413_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoiceanswer',
            name='answers',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='textanswer',
            name='answer_text',
            field=models.CharField(max_length=1028, null=True),
        ),
        migrations.AlterField(
            model_name='yesnoanswer',
            name='yes',
            field=models.NullBooleanField(),
        ),
    ]
