# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0006_auto_20160414_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='answers',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=512),
        ),
    ]
