# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0007_auto_20160414_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='index',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='questionaire',
            name='number',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
