# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionaire', '0008_auto_20160414_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionaire',
            old_name='number',
            new_name='size',
        ),
        migrations.AddField(
            model_name='question',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionaire.Questionaire'),
        ),
    ]
